### ISSUE TITLE
It's not about resolv.conf file.

### ISSUE THREAD

**Issue by eyeamnoob** [ArmanTaheriGhaleTaki/best403unlocker#12]
Hey everyone,
I'm really excited to see my community getting involved in some awesome open source projects like this one. I was just wondering, does this tool support resolvectl? It doesn't use the /etc/resolv.conf file and instead has its own config file. So just changing /etc/resolv.conf might not be enough or even recommended. Hope you all are doing great.

**Comment by ArmanTaheriGhaleTaki** [comment]
by default alpine docker image doesn't have **systemd-resolved.service** at this time so **resolvectl** is not working in this case, but for setting the suggested DNS discovered by this project you should follow the corresponding instruction related to your operating system or linux distribution

**Comment by eyeamnoob** [comment]
Thanks for your answer.
So this tool doesn't apply suggested DNS. I get it.
