### ISSUE TITLE
Show the best DNS ping

### ISSUE THREAD

**Issue by SinaSn** [ArmanTaheriGhaleTaki/best403unlocker#37]
Show the ping next to the current best DNS.

**Comment by ArmanTaheriGhaleTaki** [comment]
Thank you for the suggestion, but I believe this feature may not be particularly useful in this context. The ping measurement shows the connection quality between your device and the DNS server. However, for this project, the primary metric of interest is the download speed from the endpoint that the end user is trying to reach.

It's possible that a DNS server with a higher ping could still provide faster download speeds for the actual content. Therefore, the ping to the DNS server may not be an accurate indicator of the overall performance or speed of downloading from the targeted endpoint.
